### ISSUE TITLE
Newest Version of GCC on Arch Linux Prevented Compilation

### ISSUE THREAD

**Issue by aladar42** [TheWiseNoob/OMP#18]
Newest update on AUR doesn't compile. I'm not 100% sure if it's not on my end (I can't make anything out of compiler errors usually), but I'm reporting it just in case.

Here's the full pastebin:
https://pastebin.com/mC4p6HLa

**Comment by TheWiseNoob** [comment]
Thanks for letting me know! I'm not sure why it's working for me but not for you. I will look into this after work today.

**Comment by aladar42** [comment]
It *may* have somethign to do with this morning's updates, I'm not sure.

**Comment by TheWiseNoob** [comment]
Most of that output is just warnings that wouldn't prevent compilation, but there are two lines that are errors. I think I know why it's not compiling for you, but I won't be home for a few hours to test a fix.

**Comment by TheWiseNoob** [comment]
It IS related to the update. It does not compile for me now. gcc and g++ were updated. I'm working on solving it now.

**Comment by TheWiseNoob** [comment]
I'm pretty sure it is fixed. I just installed the new AUR release. Please let me know if it works for you when you the chance to test it!

**Comment by TheWiseNoob** [comment]
It was the update to gcc that caused it by the way. Thanks for letting me know again!

**Comment by aladar42** [comment]
Sorry for late reply, but yes, all working just fine!
