### ISSUE TITLE
Segmentation Fault Clicking Play Button Twice In Queue

### ISSUE THREAD

**Issue by noahrinehart** [TheWiseNoob/OMP#24]
Hey, while checking out this project, I noticed a bug. When I click the play button twice in a queue, the program segfaulted with this error:
```bash
omp:14175): Gtk-CRITICAL **: 00:39:34.357: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed

(omp:14175): Gtk-CRITICAL **: 00:39:34.357: gtk_tree_store_get_value: assertion 'VALID_ITER (iter, tree_store)' failed
[1]    14175 segmentation fault (core dumped)  ./omp
```
I looked into it a little, but I don't really know much about gtk. It could be just an issue with my computer...

Steps to reproduce:
1. Add 1 or more songs to the library
2. Right click a song(s) to "Queue Row(s)"
3. Hit the play button in the top left
4. Hit the play button again
5. Program crashes

**Comment by TheWiseNoob** [comment]
This issue and some other playback queue related issues are now fixed. Thanks for the reproduction instructions!
