### ISSUE TITLE
Allow Replay Gain to be Disabled 

### ISSUE THREAD

**Issue by benjamindaines** [TheWiseNoob/OMP#28]
It doesn't look like there's a way to disable replay gain

**Comment by TheWiseNoob** [comment]
Thanks for letting me know! There is not. It's a planned feature. After 0.1 is released I will be working on ReplayGain analyzing before the release of 0.2. I will make it disableable then. I'm going to have a general planned feature list for 0.2 available soon via the 0.2 Project page.
