### ISSUE TITLE
Unhelpful or Wrong Errors After Reading Certain Files

### ISSUE THREAD

**Issue by aladar42** [TheWiseNoob/OMP#40]
Some files refuse to load in OMP, even though they are valid and play fine with other software.

The errors include:

Error: /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/Touché Amoré - Stage Four/01 Flowers and You.mp3 failed to open.

Error: The mime type of /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/!!!NEW/The Future Is Analog/The Future Is Analog/1 - Sam De La Rosa - Chamaleon.wav is not valid.

Error: Failed to open /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/Joy Division/1997 - Heart and Soul/Disc 4/01 - Dead Souls (Live).flac with the mime type of .

Additionally, some files are recognized as wrong formats and throw out an error:
Error: Failed to open /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/Death In Rome - Hitparade [2xCD] (2016) [V0]/01 Love Me Forever.wav with the mime type of .
(above is actually an mp3 file)

Doesnt seem like any one particular format problem, the formats include FLAC, MP3, OGG, AIF and WAV.

**Comment by TheWiseNoob** [comment]
If you can, please email them to me if that works for you. My gmail is the same as my username here (thewisenoob).
